name: Build and Deploy to Heroku

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Login to Heroku Container Registry
      run: heroku container:login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Build and push Docker image
      run: |
        heroku container:push web -a neslo
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Release image to the app
      run: |
        heroku container:release web -a neslo
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
