name: Build, Test, and Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.2'

      - name: Install Dependencies
        run: npm install

      - name: Build Docker Image
        run: |
          docker build -t myapp:$GITHUB_SHA .
        
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v3
        with:
          start: 'docker run -p 4200:4200 myapp:$GITHUB_SHA'
          wait-on: 'http://localhost:4200'
          wait-on-timeout: 60

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Login to Heroku Container Registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Tag and Push to Heroku
        run: |
          docker tag myapp:$GITHUB_SHA registry.heroku.com/${{ secrets.HEROKU_FS_NESLO }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_FS_NESLO }}/web

      - name: Release Docker Image on Heroku
        run: heroku container:release web --app ${{ secrets.HEROKU_FS_NESLO }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
