name: Build and Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Heroku Container Registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Build and Push Unified Docker Image to Heroku
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_FS_NESLO }}/web .
          docker push registry.heroku.com/${{ secrets.HEROKU_FS_NESLO }}/web

      - name: Release Unified Docker Image
        run: heroku container:release web --app ${{ secrets.HEROKU_FS_NESLO }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
